# Generated by Django 3.2.5 on 2021-07-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_question_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
