# Generated by Django 3.2.5 on 2021-07-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210715_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(default='ABC', max_length=200),
            preserve_default=False,
        ),
    ]
